import type {
  ChannelFieldEditingConfig,
  ChannelFieldGroupId,
  ChannelFieldGroupMetaMap,
} from "./product-center-editing.types";

export const channelFieldGroupOrder = [
  "basic",
  "category",
  "media",
  "fulfillment",
  "sku",
  "compliance",
] as const satisfies readonly ChannelFieldGroupId[];

export const channelFieldGroupMeta: ChannelFieldGroupMetaMap = {
  basic: {
    label: "发品基础",
    description: "对齐 out_product_id、title、short_title。",
  },
  category: {
    label: "类目与品牌",
    description: "对齐 cats_v2、brand_id，并承接参数规则摘要。",
  },
  media: {
    label: "主图与详情",
    description: "对齐 head_imgs、desc_info.imgs、desc_info.desc。",
  },
  fulfillment: {
    label: "履约与发货",
    description: "对齐 deliver_method、运费模板和重量。",
  },
  sku: {
    label: "SKU 发售信息",
    description: "对齐 skus[].thumb_img、sale_price、stock_num、sku_code、sku_attrs。",
  },
  compliance: {
    label: "参数 / 资质 / 服务",
    description: "承接 attrs、product_qua_infos、seven_day_return、freight_insurance。",
  },
};

export const channelFieldGroupLabels: Record<ChannelFieldGroupId, string> = {
  basic: channelFieldGroupMeta.basic.label,
  category: channelFieldGroupMeta.category.label,
  media: channelFieldGroupMeta.media.label,
  fulfillment: channelFieldGroupMeta.fulfillment.label,
  sku: channelFieldGroupMeta.sku.label,
  compliance: channelFieldGroupMeta.compliance.label,
};

export const channelFieldEditingConfig: ChannelFieldEditingConfig = {
  douyin: {
    groups: {
      basic: [
        {
          fieldId: "shortTitle",
          key: "shortTitle",
          label: "带货短标题",
          required: true,
          group: "basic",
          type: "text",
          description: "用于抖音商品卡和挂车场景的短标题。",
          placeholder: "输入更适合短视频曝光的短标题",
        },
        {
          fieldId: "recommendedScene",
          key: "recommendedScene",
          label: "推荐场景",
          required: false,
          group: "basic",
          type: "select",
          description: "帮助运营快速标注推荐售卖场景。",
          options: [
            { value: "gift", label: "礼赠场景" },
            { value: "live", label: "直播主推" },
            { value: "seasonal", label: "节令上新" },
          ],
        },
      ],
      category: [],
      media: [
        {
          fieldId: "salesVideo",
          key: "salesVideo",
          label: "卖点视频",
          required: true,
          group: "media",
          type: "textarea",
          description: "可填写视频名称、脚本摘要或素材说明。",
          placeholder: "描述当前渠道使用的卖点视频内容",
        },
        {
          fieldId: "salesHighlights",
          key: "salesHighlights",
          label: "卖点亮点",
          required: false,
          group: "media",
          type: "string-array",
          description: "逐条补充最重要的卖点表达。",
          placeholder: "每条卖点单独保存",
        },
        {
          fieldId: "heroAsset",
          key: "heroAsset",
          label: "主推素材",
          required: false,
          group: "media",
          type: "asset",
          description: "从当前商品素材库里选择一个主推素材。",
          assetTypes: ["cover", "gallery", "detail"],
        },
      ],
      fulfillment: [
        {
          fieldId: "deliveryCommitment",
          key: "deliveryCommitment",
          label: "发货时效",
          required: false,
          group: "fulfillment",
          type: "select",
          description: "向渠道标注默认履约承诺。",
          options: [
            { value: "24h", label: "24小时发货" },
            { value: "48h", label: "48小时发货" },
          ],
        },
      ],
      sku: [],
      compliance: [],
    },
  },
  wechat: {
    groups: {
      basic: [
        {
          fieldId: "outProductId",
          key: "outProductId",
          label: "外部商品 ID",
          required: true,
          group: "basic",
          type: "text",
          description: "对齐 out_product_id，便于渠道侧幂等关联商品。",
          placeholder: "输入视频号商品侧的外部商品 ID",
        },
        {
          fieldId: "title",
          key: "title",
          label: "商品标题",
          required: true,
          group: "basic",
          type: "text",
          description: "对齐 title，用于视频号商品列表展示。",
          placeholder: "输入商品标题",
        },
        {
          fieldId: "shortTitle",
          key: "shortTitle",
          label: "短标题",
          required: true,
          group: "basic",
          type: "text",
          description: "对齐 short_title，用于发品页和卡片摘要展示。",
          placeholder: "输入更便于成交的短标题",
        },
      ],
      category: [
        {
          fieldId: "catsV2",
          key: "catsV2",
          label: "类目",
          required: true,
          group: "category",
          type: "text",
          description: "对齐 cats_v2，填写渠道侧类目路径。",
          placeholder: "输入类目路径或类目 ID",
        },
        {
          fieldId: "brandId",
          key: "brandId",
          label: "品牌",
          required: true,
          group: "category",
          type: "text",
          description: "对齐 brand_id，填写渠道侧品牌标识。",
          placeholder: "输入品牌 ID",
        },
        {
          fieldId: "categoryRuleSummary",
          key: "categoryRuleSummary",
          label: "类目规则摘要",
          required: true,
          group: "category",
          type: "textarea",
          description: "承接类目规则、禁限售或审核说明摘要。",
          placeholder: "补充类目规则说明",
        },
      ],
      media: [
        {
          fieldId: "headImages",
          key: "headImages",
          label: "主图",
          required: true,
          group: "media",
          type: "asset-array",
          description: "对齐 head_imgs，选择视频号主图素材。",
          assetTypes: ["cover", "gallery"],
        },
        {
          fieldId: "detailImages",
          key: "detailImages",
          label: "详情图片",
          required: true,
          group: "media",
          type: "asset-array",
          description: "对齐 desc_info.imgs，选择详情内图片素材。",
          assetTypes: ["detail"],
        },
        {
          fieldId: "detailDescription",
          key: "detailDescription",
          label: "详情文案",
          required: true,
          group: "media",
          type: "textarea",
          description: "对齐 desc_info.desc，用于详情页内容说明。",
          placeholder: "填写详情文案",
        },
      ],
      fulfillment: [
        {
          fieldId: "deliverMethod",
          key: "deliverMethod",
          label: "发货方式",
          required: true,
          group: "fulfillment",
          type: "select",
          description: "对齐 deliver_method，标记视频号侧的发货方式。",
          options: [
            { value: "express", label: "快递发货" },
            { value: "pickup", label: "门店自提" },
            { value: "same_city", label: "同城配送" },
          ],
        },
        {
          fieldId: "freightTemplate",
          key: "freightTemplate",
          label: "运费模板",
          required: true,
          group: "fulfillment",
          type: "select",
          description: "选择对应的履约运费模板。",
          options: [
            { value: "room", label: "常温模板" },
            { value: "standard", label: "标准模板" },
            { value: "cold", label: "冷链模板" },
          ],
        },
        {
          fieldId: "weight",
          key: "weight",
          label: "重量",
          required: true,
          group: "fulfillment",
          type: "number",
          description: "对齐重量信息，便于渠道履约计算。",
          placeholder: "例如 0.35",
        },
      ],
      sku: [],
      compliance: [
        {
          fieldId: "attrsSummary",
          key: "attrsSummary",
          label: "参数摘要",
          required: true,
          group: "compliance",
          type: "textarea",
          description: "承接 attrs 的摘要信息。",
          placeholder: "填写商品参数摘要",
        },
        {
          fieldId: "qualificationSummary",
          key: "qualificationSummary",
          label: "资质摘要",
          required: true,
          group: "compliance",
          type: "textarea",
          description: "承接 product_qua_infos 的摘要信息。",
          placeholder: "填写资质摘要",
        },
        {
          fieldId: "sevenDayReturn",
          key: "sevenDayReturn",
          label: "七天退货",
          required: true,
          group: "compliance",
          type: "boolean",
          description: "承接 seven_day_return 服务承诺。",
        },
        {
          fieldId: "freightInsurance",
          key: "freightInsurance",
          label: "运费险",
          required: true,
          group: "compliance",
          type: "boolean",
          description: "承接 freight_insurance 服务承诺。",
        },
      ],
    },
  },
};
