import type { SPUDetail } from "./product-center.types";

export const productCenterMock: SPUDetail[] = [
  {
    id: "spu-hanger-coffee",
    spuCode: "SPU-COFFEE-001",
    name: "冷萃挂耳咖啡礼盒",
    category: "咖啡冲饮",
    brand: "栖山实验室",
    shop: "抖音旗舰店",
    skuCount: 2,
    completionPercent: 100,
    productStatus: "ready",
    updatedAt: "2026-04-02 10:20",
    description: "适合短视频种草的冷萃挂耳组合装，包含两种风味规格。",
    tags: ["礼盒", "短视频主推", "新品"],
    skus: [
      {
        id: "sku-coffee-01",
        name: "经典拼配",
        sellerSku: "DRIP-CLASSIC",
        priceLabel: "¥59.00",
        inventory: 182,
        channelPublishing: {
          wechat: {
            skuId: "sku-coffee-01",
            skuCode: "DRIP-CLASSIC",
            salePrice: "5900",
            stockNum: 182,
            thumbImg: "asset-coffee-cover",
            skuAttrs: ["经典拼配", "500g"],
          },
        },
      },
      {
        id: "sku-coffee-02",
        name: "花果拼配",
        sellerSku: "DRIP-FRUITY",
        priceLabel: "¥69.00",
        inventory: 96,
        channelPublishing: {
          wechat: {
            skuId: "sku-coffee-02",
            skuCode: "DRIP-FRUITY",
            salePrice: "6900",
            stockNum: 96,
            thumbImg: "asset-coffee-gallery",
            skuAttrs: ["花果拼配", "500g"],
          },
        },
      },
    ],
    assets: [
      { id: "asset-coffee-cover", type: "cover", label: "封面图", status: "ready" },
      { id: "asset-coffee-gallery", type: "gallery", label: "卖点组图", status: "ready" },
      { id: "asset-coffee-detail", type: "detail", label: "详情长图", status: "ready" },
    ],
    channels: {
      douyin: {
        channel: "douyin",
        publicationStatus: "ready_to_list",
        auditStatus: "approved",
        listingStatus: "not_listed",
        missingFields: [],
        lastSyncAt: "2026-04-02 09:55",
        channelSpecificFields: [
          { fieldId: "shortTitle", label: "带货短标题", value: "春季上新冷萃挂耳礼盒", state: "ready" },
          { fieldId: "salesVideo", label: "卖点视频", value: "15 秒商品视频", state: "ready" },
        ],
      },
      wechat: {
        channel: "wechat",
        publicationStatus: "missing_fields",
        auditStatus: "not_submitted",
        listingStatus: "not_listed",
        missingFields: ["主图", "发货方式", "七天退货"],
        lastSyncAt: "2026-04-02 09:40",
        channelSpecificFields: [
          { fieldId: "outProductId", label: "外部商品 ID", value: "WX-001", state: "ready" },
          { fieldId: "title", label: "商品标题", value: "冷萃挂耳咖啡礼盒", state: "ready" },
          { fieldId: "shortTitle", label: "短标题", value: "冷萃挂耳礼盒", state: "ready" },
          { fieldId: "catsV2", label: "类目", value: "咖啡 > 挂耳咖啡", state: "ready" },
          { fieldId: "brandId", label: "品牌", value: "栖山实验室", state: "ready" },
          { fieldId: "categoryRuleSummary", label: "类目规则摘要", value: "一级类目已确认", state: "ready" },
          { fieldId: "headImages", label: "主图", value: "", state: "missing" },
          { fieldId: "detailImages", label: "详情图片", value: "详情长图", state: "ready" },
          { fieldId: "detailDescription", label: "详情文案", value: "整盒礼赠，适合冷萃场景", state: "ready" },
          { fieldId: "deliverMethod", label: "发货方式", value: "", state: "missing" },
          { fieldId: "freightTemplate", label: "运费模板", value: "标准模板", state: "ready" },
          { fieldId: "weight", label: "重量", value: "0.8", state: "ready" },
          { fieldId: "attrsSummary", label: "参数摘要", value: "口味 / 规格已确认", state: "ready" },
          { fieldId: "qualificationSummary", label: "资质摘要", value: "食品经营许可已备案", state: "ready" },
          { fieldId: "sevenDayReturn", label: "七天退货", value: "", state: "missing" },
          { fieldId: "freightInsurance", label: "运费险", value: "true", state: "ready" },
        ],
      },
    },
  },
  {
    id: "spu-coffee-trial",
    spuCode: "SPU-COFFEE-002",
    name: "慢烘焙咖啡尝鲜装",
    category: "咖啡冲饮",
    brand: "栖山实验室",
    shop: "视频号小店",
    skuCount: 1,
    completionPercent: 68,
    productStatus: "draft",
    updatedAt: "2026-04-01 18:10",
    description: "主打低门槛试喝场景，目前素材仍在补齐。",
    tags: ["待补资料"],
    skus: [{ id: "sku-coffee-03", name: "尝鲜装", sellerSku: "DRIP-TRIAL", priceLabel: "¥29.90", inventory: 56 }],
    assets: [
      { id: "asset-trial-cover", type: "cover", label: "封面图", status: "ready" },
      { id: "asset-trial-gallery", type: "gallery", label: "卖点组图", status: "missing" },
      { id: "asset-trial-detail", type: "detail", label: "详情长图", status: "missing" },
    ],
    channels: {
      douyin: {
        channel: "douyin",
        publicationStatus: "missing_fields",
        auditStatus: "not_submitted",
        listingStatus: "not_listed",
        missingFields: ["商品卖点图", "详细参数"],
        lastSyncAt: "2026-04-01 18:00",
        channelSpecificFields: [
          { fieldId: "salesGallery", label: "商品卖点图", value: "缺失", state: "missing" },
          { fieldId: "detailParams", label: "详细参数", value: "缺失", state: "missing" },
        ],
      },
      wechat: {
        channel: "wechat",
        publicationStatus: "missing_fields",
        auditStatus: "not_submitted",
        listingStatus: "not_listed",
        missingFields: [
          "商品标题",
          "类目",
          "类目规则摘要",
          "主图",
          "详情图片",
          "详情文案",
          "发货方式",
          "运费模板",
          "重量",
          "参数摘要",
          "资质摘要",
          "七天退货",
          "运费险",
          "SKU 发售信息",
        ],
        lastSyncAt: "2026-04-01 17:58",
        channelSpecificFields: [
          { fieldId: "outProductId", label: "外部商品 ID", value: "WX-TRIAL-001", state: "ready" },
          { fieldId: "title", label: "商品标题", value: "", state: "missing" },
          { fieldId: "shortTitle", label: "短标题", value: "咖啡尝鲜装", state: "ready" },
          { fieldId: "catsV2", label: "类目", value: "", state: "missing" },
          { fieldId: "brandId", label: "品牌", value: "栖山实验室", state: "ready" },
          { fieldId: "categoryRuleSummary", label: "类目规则摘要", value: "", state: "missing" },
          { fieldId: "headImages", label: "主图", value: "", state: "missing" },
          { fieldId: "detailImages", label: "详情图片", value: "", state: "missing" },
          { fieldId: "detailDescription", label: "详情文案", value: "", state: "missing" },
          { fieldId: "deliverMethod", label: "发货方式", value: "", state: "missing" },
          { fieldId: "freightTemplate", label: "运费模板", value: "", state: "missing" },
          { fieldId: "weight", label: "重量", value: "", state: "missing" },
          { fieldId: "attrsSummary", label: "参数摘要", value: "", state: "missing" },
          { fieldId: "qualificationSummary", label: "资质摘要", value: "", state: "missing" },
          { fieldId: "sevenDayReturn", label: "七天退货", value: "", state: "missing" },
          { fieldId: "freightInsurance", label: "运费险", value: "", state: "missing" },
        ],
      },
    },
  },
  {
    id: "spu-jasmine-tea",
    spuCode: "SPU-TEA-001",
    name: "茉莉轻乳茶浓缩液",
    category: "茶饮冲调",
    brand: "山野调饮",
    shop: "抖音旗舰店",
    skuCount: 3,
    completionPercent: 96,
    productStatus: "ready",
    updatedAt: "2026-04-02 08:45",
    description: "适合直播间组合售卖，主图与文案已完成，正在做渠道同步。",
    tags: ["直播间", "复购款"],
    skus: [
      { id: "sku-tea-01", name: "单瓶", sellerSku: "TEA-SINGLE", priceLabel: "¥39.00", inventory: 212 },
      { id: "sku-tea-02", name: "双瓶", sellerSku: "TEA-DOUBLE", priceLabel: "¥69.00", inventory: 148 },
      { id: "sku-tea-03", name: "四瓶礼盒", sellerSku: "TEA-GIFT", priceLabel: "¥129.00", inventory: 74 },
    ],
    assets: [
      { id: "asset-tea-cover", type: "cover", label: "封面图", status: "ready" },
      { id: "asset-tea-gallery", type: "gallery", label: "卖点组图", status: "ready" },
      { id: "asset-tea-detail", type: "detail", label: "详情长图", status: "ready" },
    ],
    channels: {
      douyin: {
        channel: "douyin",
        publicationStatus: "in_review",
        auditStatus: "pending",
        listingStatus: "not_listed",
        missingFields: [],
        lastSyncAt: "2026-04-02 08:10",
        channelSpecificFields: [
          { fieldId: "shortTitle", label: "带货短标题", value: "轻乳茶浓缩液一瓶做四杯", state: "ready" },
          { fieldId: "salesVideo", label: "卖点视频", value: "审核中", state: "warning" },
        ],
      },
      wechat: {
        channel: "wechat",
        publicationStatus: "sync_error",
        auditStatus: "approved",
        listingStatus: "delisted",
        missingFields: [],
        rejectionReason: "价格带同步失败，请重新提交渠道同步。",
        lastSyncAt: "2026-04-02 08:18",
        channelSpecificFields: [
          { fieldId: "outProductId", label: "外部商品 ID", value: "WX-TEA-001", state: "ready" },
          { fieldId: "title", label: "商品标题", value: "茉莉轻乳茶浓缩液", state: "ready" },
          { fieldId: "shortTitle", label: "短标题", value: "轻乳茶浓缩液", state: "ready" },
          { fieldId: "catsV2", label: "类目", value: "茶饮 > 浓缩液", state: "ready" },
          { fieldId: "brandId", label: "品牌", value: "山野调饮", state: "ready" },
          { fieldId: "categoryRuleSummary", label: "类目规则摘要", value: "价格带与规格需同步", state: "ready" },
          { fieldId: "headImages", label: "主图", value: "封面图\n卖点组图", state: "ready" },
          { fieldId: "detailImages", label: "详情图片", value: "详情长图", state: "ready" },
          { fieldId: "detailDescription", label: "详情文案", value: "直播间组合售卖主推款", state: "ready" },
          { fieldId: "deliverMethod", label: "发货方式", value: "express", state: "ready" },
          { fieldId: "priceBand", label: "价格带", value: "同步失败", state: "warning" },
          { fieldId: "freightTemplate", label: "运费模板", value: "常温模板", state: "ready" },
          { fieldId: "weight", label: "重量", value: "1.2", state: "ready" },
          { fieldId: "attrsSummary", label: "参数摘要", value: "规格 / 口味已确认", state: "ready" },
          { fieldId: "qualificationSummary", label: "资质摘要", value: "资质齐全", state: "ready" },
          { fieldId: "sevenDayReturn", label: "七天退货", value: "true", state: "ready" },
          { fieldId: "freightInsurance", label: "运费险", value: "true", state: "ready" },
        ],
      },
    },
  },
];
