import type { SPUDetail } from "./product-center.types";

export const productCenterMock: SPUDetail[] = [
  {
    id: "spu-hanger-coffee",
    spuCode: "SPU-COFFEE-001",
    name: "冷萃挂耳咖啡礼盒",
    category: "咖啡冲饮",
    brand: "栖山实验室",
    shop: "抖音旗舰店",
    skuCount: 2,
    completionPercent: 100,
    productStatus: "ready",
    updatedAt: "2026-04-02 10:20",
    description: "适合短视频种草的冷萃挂耳组合装，包含两种风味规格。",
    tags: ["礼盒", "短视频主推", "新品"],
    skus: [
      { id: "sku-coffee-01", name: "经典拼配", sellerSku: "DRIP-CLASSIC", priceLabel: "¥59.00", inventory: 182 },
      { id: "sku-coffee-02", name: "花果拼配", sellerSku: "DRIP-FRUITY", priceLabel: "¥69.00", inventory: 96 },
    ],
    assets: [
      { id: "asset-coffee-cover", type: "cover", label: "封面图", status: "ready" },
      { id: "asset-coffee-gallery", type: "gallery", label: "卖点组图", status: "ready" },
      { id: "asset-coffee-detail", type: "detail", label: "详情长图", status: "ready" },
    ],
    channels: {
      douyin: {
        channel: "douyin",
        publicationStatus: "ready_to_list",
        auditStatus: "approved",
        listingStatus: "not_listed",
        missingFields: [],
        lastSyncAt: "2026-04-02 09:55",
        channelSpecificFields: [
          { label: "带货短标题", value: "春季上新冷萃挂耳礼盒", state: "ready" },
          { label: "卖点视频", value: "15 秒商品视频", state: "ready" },
        ],
      },
      wechat: {
        channel: "wechat",
        publicationStatus: "missing_fields",
        auditStatus: "not_submitted",
        listingStatus: "not_listed",
        missingFields: ["商品轮播图", "运费模板"],
        lastSyncAt: "2026-04-02 09:40",
        channelSpecificFields: [
          { label: "商品轮播图", value: "缺失", state: "missing" },
          { label: "运费模板", value: "未选择", state: "missing" },
        ],
      },
    },
  },
  {
    id: "spu-coffee-trial",
    spuCode: "SPU-COFFEE-002",
    name: "慢烘焙咖啡尝鲜装",
    category: "咖啡冲饮",
    brand: "栖山实验室",
    shop: "视频号小店",
    skuCount: 1,
    completionPercent: 68,
    productStatus: "draft",
    updatedAt: "2026-04-01 18:10",
    description: "主打低门槛试喝场景，目前素材仍在补齐。",
    tags: ["待补资料"],
    skus: [{ id: "sku-coffee-03", name: "尝鲜装", sellerSku: "DRIP-TRIAL", priceLabel: "¥29.90", inventory: 56 }],
    assets: [
      { id: "asset-trial-cover", type: "cover", label: "封面图", status: "ready" },
      { id: "asset-trial-gallery", type: "gallery", label: "卖点组图", status: "missing" },
      { id: "asset-trial-detail", type: "detail", label: "详情长图", status: "missing" },
    ],
    channels: {
      douyin: {
        channel: "douyin",
        publicationStatus: "missing_fields",
        auditStatus: "not_submitted",
        listingStatus: "not_listed",
        missingFields: ["商品卖点图", "详细参数"],
        lastSyncAt: "2026-04-01 18:00",
        channelSpecificFields: [
          { label: "商品卖点图", value: "缺失", state: "missing" },
          { label: "详细参数", value: "缺失", state: "missing" },
        ],
      },
      wechat: {
        channel: "wechat",
        publicationStatus: "missing_fields",
        auditStatus: "not_submitted",
        listingStatus: "not_listed",
        missingFields: ["主图视频"],
        lastSyncAt: "2026-04-01 17:58",
        channelSpecificFields: [{ label: "主图视频", value: "缺失", state: "missing" }],
      },
    },
  },
  {
    id: "spu-jasmine-tea",
    spuCode: "SPU-TEA-001",
    name: "茉莉轻乳茶浓缩液",
    category: "茶饮冲调",
    brand: "山野调饮",
    shop: "抖音旗舰店",
    skuCount: 3,
    completionPercent: 96,
    productStatus: "ready",
    updatedAt: "2026-04-02 08:45",
    description: "适合直播间组合售卖，主图与文案已完成，正在做渠道同步。",
    tags: ["直播间", "复购款"],
    skus: [
      { id: "sku-tea-01", name: "单瓶", sellerSku: "TEA-SINGLE", priceLabel: "¥39.00", inventory: 212 },
      { id: "sku-tea-02", name: "双瓶", sellerSku: "TEA-DOUBLE", priceLabel: "¥69.00", inventory: 148 },
      { id: "sku-tea-03", name: "四瓶礼盒", sellerSku: "TEA-GIFT", priceLabel: "¥129.00", inventory: 74 },
    ],
    assets: [
      { id: "asset-tea-cover", type: "cover", label: "封面图", status: "ready" },
      { id: "asset-tea-gallery", type: "gallery", label: "卖点组图", status: "ready" },
      { id: "asset-tea-detail", type: "detail", label: "详情长图", status: "ready" },
    ],
    channels: {
      douyin: {
        channel: "douyin",
        publicationStatus: "in_review",
        auditStatus: "pending",
        listingStatus: "not_listed",
        missingFields: [],
        lastSyncAt: "2026-04-02 08:10",
        channelSpecificFields: [
          { label: "带货短标题", value: "轻乳茶浓缩液一瓶做四杯", state: "ready" },
          { label: "卖点视频", value: "审核中", state: "warning" },
        ],
      },
      wechat: {
        channel: "wechat",
        publicationStatus: "sync_error",
        auditStatus: "approved",
        listingStatus: "delisted",
        missingFields: [],
        rejectionReason: "价格带同步失败，请重新提交渠道同步。",
        lastSyncAt: "2026-04-02 08:18",
        channelSpecificFields: [
          { label: "价格带", value: "同步失败", state: "warning" },
          { label: "运费模板", value: "常温模板", state: "ready" },
        ],
      },
    },
  },
];
